### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by chasemccoy** [chasemccoy/designsystems.dev#4]
@danoc Just starting a place for us to chat about what we want this to turn into. This project is pretty low priority for me, so things might move slowly on my end. 

Figured we could start brainstorming what we want this to be, what type of content we want to have, how we want to organize it, etc. I went ahead and started up a bare bones Gatsby site that we can build on when we're ready.

**Comment by danoc** [comment]
Awesome! 

Here's a list of resources I've found helpful for design systems development work:

* [Nicolas Gallagher - Twitter Lite, React Native, and Progressive Web Apps](https://www.youtube.com/watch?v=tFFn39lLO-U)
* [Pure UI](https://rauchg.com/2015/pure-ui)
* [Falling Into The Pit of Success](https://blog.codinghorror.com/falling-into-the-pit-of-success/)
* [Defining Component APIs in React](https://jxnblk.com/blog/defining-component-apis-in-react/)
* [Sebastian Markbage: Minimal API Surface Area | JSConf EU 2014](https://www.youtube.com/watch?v=4anAwXYqLG8)
* [Ian Feather: Reducing Complexity With a Component API (2014)](https://www.youtube.com/watch?v=XNoX1FRZ8kE)

The last two are 5+ years old, but the concepts are still applicable today.

**Comment by chasemccoy** [comment]
Nice! All of those are great (especially Pure UI, it's one of my favs). 

Was thinking of something — we should probably include a message on the site that dev stuff is just _one slice_ of design systems work. Definitely want to call out that design systems are just as much about solving people problems as they are about solving design/dev ones. 

I'll round up some of my links soon and drop them here! Wonder if we wanna include any tools as well? Was thinking of things like https://sketch.systems

**Comment by danoc** [comment]
Yeah, I think tools would be great.

Links to codebases of public design systems may be helpful, too.

**Comment by chasemccoy** [comment]
- [Design System APIs and the Developer Experience - Diana Mounter - Design Systems London](https://www.youtube.com/watch?v=hftvh9SNEZQ&feature=youtu.be)
- [Tokens in Design Systems](https://medium.com/eightshapes-llc/tokens-in-design-systems-25dd82d58421)

**Tools:**
- [Sketch.systems](https://sketch.systems)
- [Styled System](https://styled-system.com)
- [Storybook](https://storybook.js.org)
- [MDX](https://mdxjs.com)
- [Abstract](https://www.goabstract.com/)
- [Style Dictionary](https://amzn.github.io/style-dictionary)

**Comment by chasemccoy** [comment]
@danoc I got this setup so that commits/PRs to master will auto-deploy to https://designsystemsdev.netlify.com 

Any thoughts on a lightweight CMS for this? I was thinking of maybe just using Airtable to store/update the data.

**Comment by danoc** [comment]
That sounds good to me!

**Comment by chasemccoy** [comment]
@danoc Okay, Airtable should be setup now! If you wanna run the site you will need to place a `.env` file in the root of the project and include an API key like this: `AIRTABLE_API_KEY={your key here}`

What's a good email for you? I can invite you to the Airtable as a collaborator.

**Comment by chasemccoy** [comment]
Never mind, I set an invite to the email on your GitHub profile (daniel at danoc dot me)
